from dataclasses import dataclass
from enum import Enum


class Category(Enum):
    business = 1,
    entertainment = 2,
    politics = 3,
    sport = 4,
    tech = 5


@dataclass
class Document:
    """Class for storing documents, their reference summaries and the generated summaries from the IR system """
    id: int
    category: str
    text: str #actual text content of document from "News Articles" directory
    referenceSummary: str #reference summary from "Summaries Folder"
    summary: str #our own summary generated by our IR system
